### ISSUE TITLE
Opening bracket not colored in coffeescript string interpolation

### ISSUE THREAD

**Issue by olmokramer** [jrattray13/swackets#2]
![swackets3](https://cloud.githubusercontent.com/assets/3612514/10308980/efdec534-6c39-11e5-87f4-f926e7862e93.png) ![swackets4](https://cloud.githubusercontent.com/assets/3612514/10308981/eff2b4f4-6c39-11e5-9a32-8d17b9d7478e.png)
![swackets5](https://cloud.githubusercontent.com/assets/3612514/10309027/5d38e2ae-6c3a-11e5-8ecd-df92d7cb40a0.png)

The images say it all... the opening bracket isn't colored inside coffeescript/javascript string interpolation, and it gets really messy when the string is inside other blocks. It doesn't happen with brackets in regular strings. Since the interpolation brackets can also span multiple lines and/or be nested, I think they should also be colored as well.

**Comment by jrattray13** [comment]
Thanks i'll look into it asap :) Sorry for inconvience.

**Comment by jrattray13** [comment]
Should be fixed now 0.5.1

**Comment by olmokramer** [comment]
Awesome! Thanks :)
