### ISSUE TITLE
Thrown off by ruby's string interpolation brackets

### ISSUE THREAD

**Issue by dkniffin** [jrattray13/swackets#21]
The swackets logic seems to be thrown off by ruby's string interpolation brackets (`#{}`):

![image](https://cloud.githubusercontent.com/assets/1680080/19353868/c6c11c32-9132-11e6-8f8e-e3e113bc2864.png)

As you can see, the second line renders fine, but the first doesn't recognize the `#{` as an open bracket.

This could probably also be fixed by resolving #18, and not trying to match any brackets inside of strings.

**Comment by Charlotteis** [comment]
@dkniffin mind adding '${' to your PR to fix the new JS string interpolation too? :D

**Comment by dkniffin** [comment]
@Charlotteis 👍 I added that one as well.

**Comment by Charlotteis** [comment]
@dkniffin thanks!

**Comment by dkniffin** [comment]
Hmm. Now that this is fixed, I'm noticing a broader issue. Swackets is actually thrown off by an "special" brackets.

Some examples:

![image](https://cloud.githubusercontent.com/assets/1680080/19522934/f2659184-95e6-11e6-9cb0-6a95f44a531b.png)

I'm gonna take a stab at fixing these cases as well.
