### ISSUE TITLE
Deprecated selector in `swackets/styles/swackets.less`

### ISSUE THREAD

**Issue by 8-uh** [jrattray13/swackets#29]
In `swackets/styles/swackets.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host atom-text-editor .highlight.highlight-selected .region,
atom-text-editor atom-text-editor .highlight.highlight-selected .region,
atom-text-editor::shadow atom-text-editor .highlight.highlight-selected .region` => `:host atom-text-editor .highlight.highlight-selected .region,
atom-text-editor atom-text-editor .highlight.highlight-selected .region,
atom-text-editor.editor atom-text-editor .highlight.highlight-selected .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by DonRichards** [comment]
Same issue.

**Comment by arjunsrinivasan1997** [comment]
I have had the same issue.

**Comment by peregrinogris** [comment]
@jrattray13 I think I fixed this in #34, would you like to take a look at the PR?

**Comment by jrattray13** [comment]
Sure i'll give it a try asap thanks for investigating
