### ISSUE TITLE
Support for parenthesis?

### ISSUE THREAD

**Issue by bordeltabernacle** [jrattray13/swackets#3]
It's be great if this also worked with parenthesis.  Would make working with Clojure a lot nicer.  Any thoughts on adding this?

**Comment by jrattray13** [comment]
Great suggestion, also had a friend mention this so will look into it.

However since I don't want it 'clashing' with the bracket colors perhaps I will make it toggle-able or just an setting, not default. -With fewer (but configurable) colours too.

**Comment by bordeltabernacle** [comment]
Oh great, toggle-able sounds good, I can see how it could clash with brackets and undermine their visual focus.  Could the brackets be toggle-able also do you think, so you could have the parens instead of brackets?

Or maybe that would be a different thing, (swarens) perhaps?

**Comment by jrattray13** [comment]
swarens... I like it :smirk: But not quite the same ring to it. We'll see how it goes when its toggle-able, perhaps there are some spare colors we can use :+1:

**Comment by olmokramer** [comment]
You could even make them toggle-able on a per-scope basis :) So one could turn them off for JavaScript, but leave them on for other languages.

And while you're adding support for parens, could you also do the square brackets: `[]`? :grin:

**Comment by LoganBarnett** [comment]
Instead of explicitly supporting `[]`, `()`, and others, maybe we could have a configurable matching characters setting so we can colorize any whacky syntax we like.

For example, a C#/Java-esque construct:
```java
List<Map<String, Maybe<Foo>>>
```

**Comment by johngeorgewright** [comment]
:+1: for a per language, configurable selection of "swackets". Maybe in the future they could even be done with regexp? Then you could match all kinds of funcky things like html tags.

**Comment by sjlevine** [comment]
Very nice package, thanks for your work!

I'd also like to voice my support for parenthesis coloring. I've been working on some Atom packages to make Atom more friendly for Common Lisp, and rainbow parentheses are a feature I really miss from Emacs.

Thanks again!

**Comment by CiaranReen** [comment]
I also would like parenthesis support for this package please. +1

**Comment by jrattray13** [comment]
Should be working now :+1: in 0.8 release, thanks and sorry for delay!

**Comment by yakiang** [comment]
why can't it just support colorful brackets and parentheses both :cry:

**Comment by jrattray13** [comment]
I will possible add an option for both to be enabled this weekend, however I am hesistant due to the mass amount of color on the page but I will look into it (Perhaps also add another color to the mix too, not enough for both).

**Comment by yakiang** [comment]
Thanks, look forward towards that!
