### ISSUE TITLE
display vanishes

### ISSUE THREAD

**Issue by aero-no1-ks** [jrattray13/swackets#46]
from today, once I click the editor, everything vanishes...

**Comment by hvmiller** [comment]
I'm having the same issue since updating other packages

**Comment by digitalsms** [comment]
Also getting this with 1.19 x64 stable on Win7. There's no error message, the display just immediately goes blank once you click inside the editor.

That, or I'll get the uncaught TypeError from bug #47.

**Comment by dbledayr** [comment]
Appears in affiliation with the 1.19 release which has huge changes to rendering. Sucks to have to click the disable button, but work must get done.

**Comment by jrattray13** [comment]
Yep sorry, will try to investigate this weekend

**Comment by shikelong** [comment]
Yes. After Atom 1.19, swackets will cause text disappear after click on the editor.

**Comment by KCN8** [comment]
I've had a bunch of friends and myself have the same issue, particularly after merge conflicts. I dig swackets though. I hope this gets fixed! Thanks for putting it out there in the first place.

**Comment by EthanBannister** [comment]
I also had to disable this due to the vanishing text within the editor.  It's too bad.  This was really a top-notch package for Atom.

I will keep a lookout in case a fix created.

**Comment by jrattray13** [comment]
Should be fixed now update swackets and atom! Let me know please thanks! Sorry for inconvience, been busy!

**Comment by aero-no1-ks** [comment]
It works! Thank you :)
