### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by yhmgood0130** [jrattray13/swackets#47]
/Users/Yang/.atom/packages/swackets/lib/swackets-view.coffee:111

TypeError: Cannot read property 'dataset' of null
    at SwacketsView.module.exports.SwacketsView.sweatifyLineGroups (/Users/Kik/.atom/packages/swackets/lib/swackets-view.coffee:111:57)
    at SwacketsView.module.exports.SwacketsView.sweatify (/Users/Kim/.atom/packages/swackets/lib/swackets-view.coffee:90:10)
    at /Users/Kim/.atom/packages/swackets/lib/swackets-view.coffee:1:1

It started happening after updated to 1.19

**Comment by solobat** [comment]
+1

**Comment by Wombosvideo** [comment]
This error even makes it unable to use atom properly. Deinstalled for now, keep me posted.

**Comment by opponitur** [comment]
+1

**Comment by amandeepmittal** [comment]
+1

**Comment by pankajso** [comment]
+1

**Comment by Foxford13** [comment]
+1

**Comment by mixn** [comment]
+1

**Comment by NickCelaya** [comment]
+1

**Comment by azz0r** [comment]
+1

**Comment by sultanhq** [comment]
+1

**Comment by HRSAstro** [comment]
+1

**Comment by Alnoa** [comment]
+1

**Comment by bkazmer** [comment]
+1

**Comment by arcs-** [comment]
+1

**Comment by DonRichards** [comment]
+1

**Comment by carb0nknight** [comment]
+1

**Comment by MiguelDotL** [comment]
+1

**Comment by pankajso** [comment]
Quick work around to use atom, remove the swackets package. 
`Menu -> Atom -> Preferences... -> Packages -> `
Then look for `swackets`,  next step is to `Disable` it **OR** `Uninstall` it
Now you are ready to use Atom without this error.
You can enable this package once this issue is fixed. 
I hope this helps

**Comment by bsussman** [comment]
for those of use who cannot disable from within atom (I am on 1.19.1 and swackets makes input impossible because it throws alerts when I  try):
`apm disable swackets` at the commandline works :)

**Comment by nwootton** [comment]
+1

**Comment by AfroSpartan** [comment]
This seems to cause the editor to be set to 'display:none;' so you can't actually use atom.

**Comment by jrattray13** [comment]
FINALLYYYYYY some spare time!

Should be fixed now update swackets and atom! Let me know please thanks! Sorry for inconvience, been busy!

**Comment by Wombosvideo** [comment]
Great, thank you 👍

**Comment by amandeepmittal** [comment]
Thanks.
