### ISSUE TITLE
Any alternatives available?

### ISSUE THREAD

**Issue by kirillseva** [jrattray13/swackets#51]
Once you start using swackets you can't really go back. But seeing that https://github.com/jrattray13/swackets/pull/50 is still under review for weeks, it looks like the dev is too busy with real life or other commitments, and the project is basically abandoned.

Who has moved on to other plugins? Maybe there is a working fork? Share your recommendations in this issue

**Comment by jrattray13** [comment]
Should be fixed now update swackets and atom! Let me know please thanks! Sorry for inconvience, been busy!

**Comment by bsussman** [comment]
Works for me - atom 1.19.7 and 1.20.0-beta7

**Comment by kirillseva** [comment]
@jrattray13 you the best. Let me know if/how I can buy you a beer
